name: SpecializedCrates
author: Ztowne13
version: 2.12.3.1 - BETA 2
main: me.ztowne13.customcrates.SpecializedCrates
api-version: 1.13
description: A 100% customizable crate plugin for your server.
softdepend: [HolographicDisplays,IndividualHolograms,Holograms,Citizens,CMI,PlaceholderAPI,Multiverse-Core,Vault]
commands:
  scrates:
    description: All commands for the specialized crates plugin.
    aliases: [ccrates,crates,specializedcrates,sc]
  keys:
    description: See how many virtual keys you have for your crates.
    aliases: [skeys,cratekey,cratekeys]
  rewards:
    description: Open a rewards menu for a crate